### ISSUE TITLE
WebSocketError

### ISSUE THREAD

**Issue by ryujimorimoto** [agrinman/tunnelto#67]
When I launch tunnelto, I run into a WebSocketError.
It worked fine until the day before, but suddenly it stopped working.

```
🌎 Opening remote tunnel...
> Ready on http://localhost:8082 , https://forestbook.tunne
 ERROR tunnelto > Control error: WebSocketError(Tls(Native(Error { code: -9806, message: "connection closed via error" }))). Retrying in 5 seconds.
```

Could you give me a way to solve this problem?

**Comment by mbcrute** [comment]
I also am experiencing this, since about 3 PM EDT on July 28th...

```sh
» tunnelto --port 9909 --verbose
 INFO  tunnelto::config > Control Server URL: wss://wormhole.tunnelto.dev:443/wormhole
 DEBUG tunnelto::update > Using latest version.
 ERROR tunnelto         > Control error: WebSocketError(Protocol(HandshakeIncomplete)). Retrying in 5 seconds.
 INFO  tunnelto         > restarting wormhole
 ERROR tunnelto         > Control error: WebSocketError(Tls(Native(Error { code: -9806, message: "connection closed via error" }))). Retrying in 5 seconds.
 INFO  tunnelto         > restarting wormhole
 ERROR tunnelto         > Control error: WebSocketError(Http(Response { status: 502, version: HTTP/1.1, headers: {"server": "Fly/eefa7631 (2022-07-29)", "via": "1.1 fly.io", "fly-request-id": "01G9526VG7HT6KA4PX00105KVG-iad", "content-length": "0", "date": "Fri, 29 Jul 2022 13:27:10 GMT"}, body: None })). Retrying in 5 seconds.
 INFO  tunnelto         > restarting wormhole
🌍 Opening remote tunnel...
```

Lather. Rinse. Repeat. I sent an email to support yesterday but have yet to receive a response.

**Comment by malikid** [comment]
+1

**Comment by drazen-popov-lepaya** [comment]
+1

**Comment by ryujimorimoto** [comment]
The error is now resolved when you access it after a while.
The cause of this error is unknown.

**Comment by drazen-popov-lepaya** [comment]
Worked a little bit, but it is still broken. 
  
 ERROR tunnelto > Control error: WebSocketError(Protocol(ResetWithoutClosingHandshake)). Retrying in 5 seconds.
 ERROR tunnelto > Control error: WebSocketError(Protocol(ResetWithoutClosingHandshake)). Retrying in 5 seconds.
 ERROR tunnelto > Control error: WebSocketError(Http(Response { status: 502, version: HTTP/1.1, headers: {"server": "Fly/b2c77cc8 (2022-07-31)", "via": "1.1 fly.io", "fly-request-id": "01G9CNVDE90TZF128RRNYG4M74-ams", "content-length": "0", "date": "Mon, 01 Aug 2022 12:24:49 GMT"}, body: None })). Retrying in 5 seconds.
 ERROR tunnelto > Control error: WebSocketError(Http(Response { status: 502, version: HTTP/1.1, headers: {"server": "Fly/b2c77cc8 (2022-07-31)", "via": "1.1 fly.io", "fly-request-id": "01G9CNVKFS5CDKR7WENPQ5MCAH-ams", "content-length": "0", "date": "Mon, 01 Aug 2022 12:25:09 GMT"}, body: None })). Retrying in 5 seconds.
 ERROR tunnelto > Control error: WebSocketError(Http(Response { status: 502, version: HTTP/1.1, headers: {"server": "Fly/b2c77cc8 (2022-07-31)", "via": "1.1 fly.io", "fly-request-id": "01G9CNW6P8707QSXEJFBKHAV8R-ams", "content-length": "0", "date": "Mon, 01 Aug 2022 12:25:25 GMT"}, body: None })). Retrying in 5 seconds.

**Comment by mbcrute** [comment]
Still not working for me either. I've not gotten a response from the Twitter account or the email I sent to support so I'm canceling my account and self-hosting.

**Comment by malikid** [comment]
Still getting errors...

**Comment by KTruong008** [comment]
Just started getting this error this morning. Also had some odd loading issues prior where it'd take minutes to load pages that took seconds just days ago.

**Comment by zerobit-tech** [comment]
Same error for me also.
anyone found a solution for this issue?

**Comment by onlysumitg** [comment]
Same issue for me.
anyone found a solution for this issue?

**Comment by j0no** [comment]
I'm getting this issue as well.

**Comment by iGhoneim** [comment]
I'm getting "An existing connection was forcibly closed by the remote host."

` ERROR tunnelto > Control error: WebSocketError(Tls(Native(Os { code: 10054, kind: ConnectionReset, message: "An existing connection was forcibly closed by the remote host." }))). Retrying in 5 seconds.`

**Comment by Ryusuke-Kawasaki** [comment]
Hi.
I'm getting same issue.  After I ran  tunnelto command, I got the following error message.
```
 ERROR tunnelto > Control error: WebSocketError(Tls(Native(Error { code: -9806, message: "connection closed via error" }))). Retrying in 5 seconds.
```

**Comment by Ryusuke-Kawasaki** [comment]
I ran the tunneldev command again today. 
As a result, I confirmed that the following problems reported yesterday did not occur and the tunneldev command was executed successfully.
```
ERROR tunnelto > Control error: WebSocketError(Tls(Native(Error { code: -9806, message: "connection closed via error" }))). Retrying in 5 seconds.
```

**Comment by j0no** [comment]
I ran a tunnel and I no longer get the error.
